### ISSUE TITLE
on run python badrobo.py

### ISSUE THREAD

**Issue by ingnrcs** [jaleelx98/Bad-Robo#12]
Traceback (most recent call last):
  File "badrobo.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 5, in <module>
ImportError: No module named FunctionData.somefun

**Comment by h4ck3r1b0y** [comment]
run  python badrobo.py 
Traceback (most recent call last):
  File "badrobo.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 5, in <module>
ImportError: No module named FunctionData.somefun


why get error
