### ISSUE TITLE
Ig

### ISSUE THREAD

**Issue by anqazmn70** [jaleelx98/Bad-Robo#9]

**Comment by Farhadgh** [comment]
ERROR - Request returns 429 error!

**Comment by ingnrcs** [comment]
Traceback (most recent call last):
  File "badrobo.py", line 8, in <module>
    eval(compile(base64.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 5, in <module>
ImportError: No module named FunctionData.somefun
